#!/bin/bash

rm -rf lib
mkdir lib

tsc -p tsconfig.json

tsc -p tsconfig-cjs.json

FILES=$(find lib/cjs -name "*.js")

for FILE in $FILES; do

  terser $FILE --ecma 5 -m -c -o $FILE

done

touch lib/cjs/package.json
cat >lib/cjs/package.json <<!EOF
{
    "type": "commonjs"
}
!EOF

touch lib/mjs/package.json
cat >lib/mjs/package.json <<!EOF
{
    "type": "module"
}
!EOF
